import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../src/components/molecules/Card/Card'
import IconButton from '../src/components/atoms/IconButton/IconButton'
import SearchBar from '../src/components/molecules/SearchBar/SearchBar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.cards}>
        <Card 
          imageUrl="https://www.backpackeninazie.nl/wp-content/uploads/2012/11/Koh-Phi-Phi-1.jpg"
          location="Thailand"
          price="$1,480"
          title="Phi Phi Islands"
          />
        <Card 
          imageUrl="https://www.makemytrip.com/travel-guide/media/dg_image/maldives/Kudahuvadhoo.jpg"
          location="Maldives"
          price="$1,480"
          title="Kudahuvadhoo Island"
          />
        </div>
        <IconButton icon="calendar" />
        <IconButton icon="compas" />
        <IconButton icon="person" />
        <IconButton icon="settings" />
        <IconButton icon="power" />
        <IconButton icon="home" active />
        <SearchBar />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
